### ISSUE TITLE
[Bug/Security] Addition overflow panic in `ProvingKey::from_bytes_le`

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/snarkVM#1087]
# Addition overflow panic in `ProvingKey::from_bytes_le`

We (@fuzzinglabs) found an addition overflow panic while fuzzing `ProvingKey::from_bytes_le`.

```sh
thread 'main' panicked at 'attempt to add with overflow', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/num/mod.rs:885:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Behavior

An error should be returned instead.

## Your Environment

-  SnarkVM commit: 44b1802589b3cdcd84acc0752210b212f203dfc3
-  cargo 1.66.0-nightly (082503982 2022-09-13) 
-  Ubuntu 20.04

## Steps to Reproduce

Testing program:
``` rust
use snarkvm_compiler::ProvingKey;
use snarkvm_wasm::network::Testnet3;
use snarkvm_wasm::prelude::FromBytes;

pub type CurrentNetwork = Testnet3;

fn main() {
    let data = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 149, 0, 253, 0, 0, 0, 0, 0, 0];
    let _ = ProvingKey::<CurrentNetwork>::from_bytes_le(&data);
}
```

Build and run:
``` sh
$ RUST_BACKTRACE=1 cargo run

    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/debug add_overflow_provingkey_from_bytes_le.crash dd`
thread 'main' panicked at 'attempt to add with overflow', /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/num/mod.rs:902:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:48:5
   3: core::num::<impl usize>::next_power_of_two
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/num/uint_macros.rs:2203:13
   4: snarkvm_algorithms::fft::domain::EvaluationDomain<F>::compute_size_of_domain
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/fft/domain.rs:151:20
   5: <snarkvm_algorithms::snark::marlin::ahp::indexer::circuit::Circuit<F,MM> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/ahp/indexer/circuit.rs:145:38
   6: snarkvm_utilities::serialize::impls::<impl snarkvm_utilities::serialize::traits::CanonicalDeserialize for alloc::sync::Arc<T>>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/impls.rs:301:21
   7: snarkvm_utilities::serialize::traits::CanonicalDeserialize::deserialize_compressed
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/traits.rs:161:9
   8: <snarkvm_algorithms::snark::marlin::data_structures::circuit_proving_key::CircuitProvingKey<E,MM> as snarkvm_utilities::bytes::FromBytes>::read_le
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/data_structures/circuit_proving_key.rs:59:23
   9: snarkvm_compiler::snark::proving_key::bytes::<impl snarkvm_utilities::bytes::FromBytes for snarkvm_compiler::snark::proving_key::ProvingKey<N>>::read_le
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/vm/compiler/src/snark/proving_key/bytes.rs:29:27
  10: snarkvm_utilities::bytes::FromBytes::from_bytes_le
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/bytes.rs:78:12
  11: debug::main
             at ./src/main.rs:74:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

## Detailed behavior (RUST_BACKTRACE=full)
``` sh
thread 'main' panicked at 'attempt to add with overflow', /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/num/mod.rs:902:5
stack backtrace:
   0:     0x55fbeb6e1450 - std::backtrace_rs::backtrace::libunwind::trace::h3857ef565af39398
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x55fbeb6e1450 - std::backtrace_rs::backtrace::trace_unsynchronized::hbdcd051de7f77d0f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fbeb6e1450 - std::sys_common::backtrace::_print_fmt::h23be2adc86b0a876
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55fbeb6e1450 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b060ccd6bd6b034
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55fbeb6fca6e - core::fmt::write::h8c66ea5bcce6741d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/fmt/mod.rs:1202:17
   5:     0x55fbeb6debe5 - std::io::Write::write_fmt::h4eb4d78dd880f1b9
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/io/mod.rs:1679:15
   6:     0x55fbeb6e2c83 - std::sys_common::backtrace::_print::h95ae1478fe0e51b5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55fbeb6e2c83 - std::sys_common::backtrace::print::h14585209d1e15fd7
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55fbeb6e2c83 - std::panicking::default_hook::{{closure}}::h8113d7aba344b100
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:295:22
   9:     0x55fbeb6e296f - std::panicking::default_hook::hc8f6609e883c8b5a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:314:9
  10:     0x55fbeb6e332a - std::panicking::rust_panic_with_hook::h3db30b700f89d22f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:698:17
  11:     0x55fbeb6e31e1 - std::panicking::begin_panic_handler::{{closure}}::h5f3b99931d65aa88
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:586:13
  12:     0x55fbeb6e18fc - std::sys_common::backtrace::__rust_end_short_backtrace::h444863965d46291e
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55fbeb6e2f42 - rust_begin_unwind
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
  14:     0x55fbeb521713 - core::panicking::panic_fmt::h3fce1d62b588c5f8
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
  15:     0x55fbeb5215dd - core::panicking::panic::hc5a73305e6eef9cc
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:48:5
  16:     0x55fbeb5a31b3 - core::num::<impl usize>::next_power_of_two::hf1f1fab564c9392e
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/num/uint_macros.rs:2203:13
  17:     0x55fbeb56d40e - snarkvm_algorithms::fft::domain::EvaluationDomain<F>::compute_size_of_domain::h52c82d8eb499dfcf
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/fft/domain.rs:151:20
  18:     0x55fbeb545e6b - <snarkvm_algorithms::snark::marlin::ahp::indexer::circuit::Circuit<F,MM> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode::h576d3131a8738fde
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/ahp/indexer/circuit.rs:145:38
  19:     0x55fbeb524114 - snarkvm_utilities::serialize::impls::<impl snarkvm_utilities::serialize::traits::CanonicalDeserialize for alloc::sync::Arc<T>>::deserialize_with_mode::hf26f4a28dde2d80f
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/impls.rs:301:21
  20:     0x55fbeb524212 - snarkvm_utilities::serialize::traits::CanonicalDeserialize::deserialize_compressed::hcc9393f5fe81656d
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/traits.rs:161:9
  21:     0x55fbeb590fac - <snarkvm_algorithms::snark::marlin::data_structures::circuit_proving_key::CircuitProvingKey<E,MM> as snarkvm_utilities::bytes::FromBytes>::read_le::h795cff1c025fd956
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/data_structures/circuit_proving_key.rs:59:23
  22:     0x55fbeb5670ac - snarkvm_compiler::snark::proving_key::bytes::<impl snarkvm_utilities::bytes::FromBytes for snarkvm_compiler::snark::proving_key::ProvingKey<N>>::read_le::hf94e2ff1a25deb5a
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/vm/compiler/src/snark/proving_key/bytes.rs:29:27
  23:     0x55fbeb56721d - snarkvm_utilities::bytes::FromBytes::from_bytes_le::h35cebb0d973485b9
                               at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/bytes.rs:78:12
  24:     0x55fbeb5727b4 - debug::main::h6b0af873b3fd696f
                               at /home/scop/Documents/aleo/aleo_fuzzing/debug/src/main.rs:74:13
  25:     0x55fbeb53f1cb - core::ops::function::FnOnce::call_once::h95b89bae7da6e4d3
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
  26:     0x55fbeb5aa80e - std::sys_common::backtrace::__rust_begin_short_backtrace::hb37ad5a3108127a2
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:122:18
  27:     0x55fbeb5240a1 - std::rt::lang_start::{{closure}}::h081de759fc50b251
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:166:18
  28:     0x55fbeb6daddf - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfe40fc07d59ff35b
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:283:13
  29:     0x55fbeb6daddf - std::panicking::try::do_call::h9af19e4004d64d3c
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:492:40
  30:     0x55fbeb6daddf - std::panicking::try::h74bd36c835ebfce4
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:456:19
  31:     0x55fbeb6daddf - std::panic::catch_unwind::hde508ca8d57519ef
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panic.rs:137:14
  32:     0x55fbeb6daddf - std::rt::lang_start_internal::{{closure}}::hb82d8430651f3e15
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:148:48
  33:     0x55fbeb6daddf - std::panicking::try::do_call::h0536fa687ed9620a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:492:40
  34:     0x55fbeb6daddf - std::panicking::try::heb2d4789806ef666
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:456:19
  35:     0x55fbeb6daddf - std::panic::catch_unwind::h271dde582afe18c5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panic.rs:137:14
  36:     0x55fbeb6daddf - std::rt::lang_start_internal::hbe9c632c931a9d3d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:148:20
  37:     0x55fbeb52407a - std::rt::lang_start::h776d2c1a4a659b95
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:165:17
  38:     0x55fbeb5727f1 - main
  39:     0x7f8580d8b083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  40:     0x55fbeb52199e - _start
  41:                0x0 - <unknown>
```

**Comment by ljedrz** [comment]
If no one else assumes control earlier, I can take a look at it tomorrow 👍.
