### ISSUE TITLE
[Bug/Security] Debug assertion panic in Function/Finalize decoding

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/snarkVM#1240]
# Debug assertion panic in Function/Finalize decoding

We (@fuzzinglabs) found a panic while fuzzing `Function::parse`.

```sh
thread 'main' panicked at 'Finalize must have less than 8 operands', /home/user/snarkVM/synthesizer/src/program/finalize/command/finalize.rs:48:9
```

## Expected Behavior

A non-panicking exit should be made.

## Your Environment

-  SnarkVM commit: dbe7111a79dbe9b16d8ab883542e15207664da43
-  cargo 1.66.0-nightly (082503982 2022-09-13) 
-  Ubuntu 20.04

## Steps to Reproduce

Testing program:
``` rust
use snarkvm::prelude::*;

fn main() {
    let s_slice = " functionrue:finalizer1035\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\";finalizerue:shl.wr4r18 intor0;pro\0\01105\0\0\0\0\0\u{6}433as\0///3 \0\0\0\0\0\0\0\0\0\01302npuu\0\0\0\u{1}\0\0\0\0e:f//35j`uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu628npuue:\0\0\0\0\u{1}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\u{7f}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0++++,+\0\0\u{c}888-2288_\u{b}\0\0\u{2}88\0++\u{b}+,+\0\0\u{c}8\0\0\0\0\0\0\0\0889\0\u{2}88\0\0\0\0\0\0\0\0\0\0\0\u{1e}\u{c}\0\0\0\0\0\0\0\0\0\0++\u{b}+,+\0\0\u{c}8\0\0\0\0\0\0\0\0\08888888888889888\0\0\0\0\0\0\0\u{1f}8";
    let _ = Function::<Testnet3>::parse(s_slice);
}

```

Build and run:
``` sh
$ RUST_BACKTRACE=1 cargo run
thread 'main' panicked at 'Finalize must have less than 8 operands', /home/user/snarkVM/synthesizer/src/program/finalize/command/finalize.rs:48:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
   2: snarkvm_synthesizer::program::finalize::command::finalize::FinalizeOperation<N,_>::operands
             at /home/user/snarkVM/synthesizer/src/program/finalize/command/finalize.rs:48:9
   3: snarkvm_synthesizer::program::function::Function<N>::add_finalize
             at /home/user/snarkVM/synthesizer/src/program/function/mod.rs:202:13
   4: snarkvm_synthesizer::program::function::parse::<impl snarkvm_console_network_environment::traits::parse::Parser for snarkvm_synthesizer::program::function::Function<N>>::parse::{{closure}}
             at /home/user/snarkVM/synthesizer/src/program/function/parse.rs:74:37
   5: nom::combinator::map_res::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-7.1.1/src/combinator/mod.rs:115:11
   6: snarkvm_synthesizer::program::function::parse::<impl snarkvm_console_network_environment::traits::parse::Parser for snarkvm_synthesizer::program::function::Function<N>>::parse
             at /home/user/snarkVM/synthesizer/src/program/function/parse.rs:56:9
   7: REPROD_parse_Function_parse::main
             at ./src/bin/REPROD_parse_Function_parse.rs:6:13
   8: core::ops::function::FnOnce::call_once
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
```

## Detailed behavior (RUST_BACKTRACE=full)
``` sh
thread 'main' panicked at 'Finalize must have less than 8 operands', /home/user/snarkVM/synthesizer/src/program/finalize/command/finalize.rs:48:9
stack backtrace:
   0:     0x561d896188c0 - std::backtrace_rs::backtrace::libunwind::trace::h3857ef565af39398
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x561d896188c0 - std::backtrace_rs::backtrace::trace_unsynchronized::hbdcd051de7f77d0f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561d896188c0 - std::sys_common::backtrace::_print_fmt::h23be2adc86b0a876
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x561d896188c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b060ccd6bd6b034
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x561d8963505e - core::fmt::write::h8c66ea5bcce6741d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/fmt/mod.rs:1202:17
   5:     0x561d896164e5 - std::io::Write::write_fmt::h4eb4d78dd880f1b9
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/io/mod.rs:1679:15
   6:     0x561d89619f43 - std::sys_common::backtrace::_print::h95ae1478fe0e51b5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x561d89619f43 - std::sys_common::backtrace::print::h14585209d1e15fd7
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x561d89619f43 - std::panicking::default_hook::{{closure}}::h8113d7aba344b100
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:295:22
   9:     0x561d89619c2f - std::panicking::default_hook::hc8f6609e883c8b5a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:314:9
  10:     0x561d8961a5ea - std::panicking::rust_panic_with_hook::h3db30b700f89d22f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:698:17
  11:     0x561d8961a4e7 - std::panicking::begin_panic_handler::{{closure}}::h5f3b99931d65aa88
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:588:13
  12:     0x561d89618d6c - std::sys_common::backtrace::__rust_end_short_backtrace::h444863965d46291e
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x561d8961a202 - rust_begin_unwind
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
  14:     0x561d8946c8a3 - core::panicking::panic_fmt::h3fce1d62b588c5f8
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
  15:     0x561d894adb6f - snarkvm_synthesizer::program::finalize::command::finalize::FinalizeOperation<N,_>::operands::had611a46911a8ea9
                               at /home/user/snarkVM/synthesizer/src/program/finalize/command/finalize.rs:48:9
  16:     0x561d8949b385 - snarkvm_synthesizer::program::function::Function<N>::add_finalize::hf45a73454cf59eb4
                               at /home/user/snarkVM/synthesizer/src/program/function/mod.rs:202:13
  17:     0x561d8954caf1 - snarkvm_synthesizer::program::function::parse::<impl snarkvm_console_network_environment::traits::parse::Parser for snarkvm_synthesizer::program::function::Function<N>>::parse::{{closure}}::hdbede850a594d5a3
                               at /home/user/snarkVM/synthesizer/src/program/function/parse.rs:74:37
  18:     0x561d894edbdd - nom::combinator::map_res::{{closure}}::h4109acb8bea37a57
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-7.1.1/src/combinator/mod.rs:115:11
  19:     0x561d8949d8b9 - snarkvm_synthesizer::program::function::parse::<impl snarkvm_console_network_environment::traits::parse::Parser for snarkvm_synthesizer::program::function::Function<N>>::parse::h92a0c0141d96448d
                               at /home/user/snarkVM/synthesizer/src/program/function/parse.rs:56:9
  20:     0x561d894a9b26 - REPROD_parse_Function_parse::main::h4cb4dd2b53a308bc
                               at /home/user/FUZZ_snarkVM/src/bin/REPROD_parse_Function_parse.rs:6:13
  21:     0x561d8954265b - core::ops::function::FnOnce::call_once::h98b32c4a0c802603
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
  22:     0x561d894985ce - std::sys_common::backtrace::__rust_begin_short_backtrace::h236b71760777480c
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:122:18
  23:     0x561d894d13f1 - std::rt::lang_start::{{closure}}::h6bdb64ba6c1cb710
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:166:18
  24:     0x561d8961357f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfe40fc07d59ff35b
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:283:13
  25:     0x561d8961357f - std::panicking::try::do_call::h9af19e4004d64d3c
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:492:40
  26:     0x561d8961357f - std::panicking::try::h74bd36c835ebfce4
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:456:19
  27:     0x561d8961357f - std::panic::catch_unwind::hde508ca8d57519ef
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panic.rs:137:14
  28:     0x561d8961357f - std::rt::lang_start_internal::{{closure}}::hb82d8430651f3e15
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:148:48
  29:     0x561d8961357f - std::panicking::try::do_call::h0536fa687ed9620a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:492:40
  30:     0x561d8961357f - std::panicking::try::heb2d4789806ef666
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:456:19
  31:     0x561d8961357f - std::panic::catch_unwind::h271dde582afe18c5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panic.rs:137:14
  32:     0x561d8961357f - std::rt::lang_start_internal::hbe9c632c931a9d3d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:148:20
  33:     0x561d894d13ca - std::rt::lang_start::h4b4ba4c9bf726f3c
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:165:17
  34:     0x561d894a9b61 - main
  35:     0x7f96be76a083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  36:     0x561d8946cb1e - _start
  37:                0x0 - <unknown>
```

**Comment by ljedrz** [comment]
This is caused by a `debug_assert`, so it's more of a logic futureproofing safeguard than a security issue.

@howardwu do we expect anyone besides the developers to build in debug mode?
