### ISSUE TITLE
[Bug/Security] Unwrap panic during the transformation of a `Projective<EdwardsParameters>` into an `Affine<EdwardsParameters>`

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/snarkVM#1286]
# Unwrap panic in `twisted_edwards_extended/affine.rs` 

We (@fuzzinglabs) found a panic during the transformation of a `Projective<EdwardsParameters>` into an `Affine<EdwardsParameters>`

```sh
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/affine.rs:323:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Behavior

Should not crash. Either return a Result or an Option

## Your Environment

-  SnarkVM commit: 6d04326dae5e75e4f35def2e92c3a55e64ca08bc
-  Rust Version (stable): cargo 1.63.0 (fd9c4297c 2022-07-01)
-  Computer OS: Ubuntu 22.04

## Steps to reproduce

Testing program:
``` rust
use snarkvm::prelude::*;
use snarkvm_curves::templates::twisted_edwards_extended::Projective;
use snarkvm_fields::PrimeField;
use snarkvm_wasm::EdwardsParameters;
use snarkvm_curves::templates::twisted_edwards_extended::Affine;

pub fn edwards_from_x_custom<P: TwistedEdwardsParameters>(data: &[u8])
where
    P::BaseField: PrimeField,
{
    let a = Projective::<P>::from_bytes_le(data);
    let a = match a {
        Ok(a) => a,
        Err(_) => return
    };
    let a = a.to_affine();
    let x = a.x;
    let _ = Affine::<P>::from_x_coordinate(x, true).unwrap();
    let _ = Affine::<P>::from_x_coordinate(x, false).unwrap();
}

fn main() {
    let data: [u8;128] = [0, 194, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 147, 26, 5, 0, 0, 0, 1, 17, 178, 126, 118, 166, 174, 122, 210, 42, 187, 10, 30, 84, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]; 
    edwards_from_x_custom::<EdwardsParameters>(&data);
}
```

Build and run:
``` sh
$ RUST_BACKTRACE=1 cargo run
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/affine.rs:323:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/option.rs:775:21
   4: <snarkvm_curves::templates::twisted_edwards_extended::affine::Affine<P> as core::convert::From<snarkvm_curves::templates::twisted_edwards_extended::projective::Projective<P>>>::from
             at /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/affine.rs:323:25
   5: <T as core::convert::Into<U>>::into
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/convert/mod.rs:552:9
   6: <snarkvm_curves::templates::twisted_edwards_extended::projective::Projective<P> as snarkvm_curves::traits::group::ProjectiveCurve>::to_affine
             at /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/projective.rs:279:9
   7: REPROD_twisted_edwards_test_from_x::edwards_from_x_custom
             at ./src/bin/REPROD_twisted_edwards_test_from_x.rs:16:13
   8: REPROD_twisted_edwards_test_from_x::main
             at ./src/bin/REPROD_twisted_edwards_test_from_x.rs:24:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace

```

## Detailed behavior (RUST_BACKTRACE=full)

``` sh
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/affine.rs:323:39
stack backtrace:
   0:     0x558b49ec6550 - std::backtrace_rs::backtrace::libunwind::trace::h3857ef565af39398
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x558b49ec6550 - std::backtrace_rs::backtrace::trace_unsynchronized::hbdcd051de7f77d0f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558b49ec6550 - std::sys_common::backtrace::_print_fmt::h23be2adc86b0a876
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x558b49ec6550 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b060ccd6bd6b034
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x558b49ee0c6e - core::fmt::write::h8c66ea5bcce6741d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/fmt/mod.rs:1202:17
   5:     0x558b49ec4225 - std::io::Write::write_fmt::h4eb4d78dd880f1b9
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/io/mod.rs:1679:15
   6:     0x558b49ec7bd3 - std::sys_common::backtrace::_print::h95ae1478fe0e51b5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x558b49ec7bd3 - std::sys_common::backtrace::print::h14585209d1e15fd7
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x558b49ec7bd3 - std::panicking::default_hook::{{closure}}::h8113d7aba344b100
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:295:22
   9:     0x558b49ec78bf - std::panicking::default_hook::hc8f6609e883c8b5a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:314:9
  10:     0x558b49ec827a - std::panicking::rust_panic_with_hook::h3db30b700f89d22f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:698:17
  11:     0x558b49ec8131 - std::panicking::begin_panic_handler::{{closure}}::h5f3b99931d65aa88
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:586:13
  12:     0x558b49ec69fc - std::sys_common::backtrace::__rust_end_short_backtrace::h444863965d46291e
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x558b49ec7e92 - rust_begin_unwind
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
  14:     0x558b49e7a8a3 - core::panicking::panic_fmt::h3fce1d62b588c5f8
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
  15:     0x558b49e7a76d - core::panicking::panic::hc5a73305e6eef9cc
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:48:5
  16:     0x558b49e93f20 - core::option::Option<T>::unwrap::h854c0aa3d3cd1313
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/option.rs:775:21
  17:     0x558b49e7ca87 - <snarkvm_curves::templates::twisted_edwards_extended::affine::Affine<P> as core::convert::From<snarkvm_curves::templates::twisted_edwards_extended::projective::Projective<P>>>::from::h637b569e814ce33a
                               at /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/affine.rs:323:25
  18:     0x558b49e7d410 - <T as core::convert::Into<U>>::into::h5d5ee8250e5f57e4
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/convert/mod.rs:552:9
  19:     0x558b49e7d3c7 - <snarkvm_curves::templates::twisted_edwards_extended::projective::Projective<P> as snarkvm_curves::traits::group::ProjectiveCurve>::to_affine::h90bf17bc2a444d80
                               at /home/user/snarkVM/curves/src/templates/twisted_edwards_extended/projective.rs:279:9
  20:     0x558b49e7bace - REPROD_twisted_edwards_test_from_x::edwards_from_x_custom::hb6c3fc3dd37db78d
                               at /home/user/FUZZ_snarkVM/src/bin/REPROD_twisted_edwards_test_from_x.rs:16:13
  21:     0x558b49e7b6ee - REPROD_twisted_edwards_test_from_x::main::hedc1c0618981671b
                               at /home/user/FUZZ_snarkVM/src/bin/REPROD_twisted_edwards_test_from_x.rs:24:5
  22:     0x558b49e7bc4b - core::ops::function::FnOnce::call_once::h417b6e01414937fa
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
  23:     0x558b49e7b3be - std::sys_common::backtrace::__rust_begin_short_backtrace::h381dab610644e159
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:122:18
  24:     0x558b49e7ac41 - std::rt::lang_start::{{closure}}::h8a55878b1bbc6b1b
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:166:18
  25:     0x558b49ec199f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfe40fc07d59ff35b
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:283:13
  26:     0x558b49ec199f - std::panicking::try::do_call::h9af19e4004d64d3c
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:492:40
  27:     0x558b49ec199f - std::panicking::try::h74bd36c835ebfce4
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:456:19
  28:     0x558b49ec199f - std::panic::catch_unwind::hde508ca8d57519ef
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panic.rs:137:14
  29:     0x558b49ec199f - std::rt::lang_start_internal::{{closure}}::hb82d8430651f3e15
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:148:48
  30:     0x558b49ec199f - std::panicking::try::do_call::h0536fa687ed9620a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:492:40
  31:     0x558b49ec199f - std::panicking::try::heb2d4789806ef666
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:456:19
  32:     0x558b49ec199f - std::panic::catch_unwind::h271dde582afe18c5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panic.rs:137:14
  33:     0x558b49ec199f - std::rt::lang_start_internal::hbe9c632c931a9d3d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:148:20
  34:     0x558b49e7ac1a - std::rt::lang_start::h313b8fc32ca623c2
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/rt.rs:165:17
  35:     0x558b49e7b721 - main
  36:     0x7fc36e887083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  37:     0x558b49e7ab1e - _start
  38:                0x0 - <unknown>
```

**Comment by ljedrz** [comment]
Since this is a crypto-specific issue I'm not going to resolve it using my usual engineering magic.

@howardwu your call

**Comment by Pratyush** [comment]
Hm this should not panic; the `inverse` operation should return `None` only when `p.is_zero()` is false, and a non-zero point that's in the subgroup has non-zero z coordinate [(`is_zero` enforces that `p.y == p.z && !p.y.is_zero()`)](https://github.com/AleoHQ/snarkvm/blob/testnet3/curves/src/templates/twisted_edwards_extended/projective.rs#L56)

**Comment by Pratyush** [comment]
Can you provide the input that causes this failure?

**Comment by CooperShield** [comment]
With this code, using snarkVM on branch testnet3, commit 8a9982ccdf574728a59d052fdfb4827c1ccfcdef:

```Rust
use snarkvm::prelude::*;
use snarkvm_curves::templates::twisted_edwards_extended::Projective;
use snarkvm_fields::PrimeField;
use snarkvm_wasm::EdwardsParameters;

pub fn edwards_from_x_custom<P: TwistedEdwardsParameters>(data: &[u8])
where
    P::BaseField: PrimeField,
{
    let a = Projective::<P>::from_bytes_le(data);
    let a = match a {
        Ok(a) => a,
        Err(_) => return
    };
    let _ = a.to_affine();
}

fn main() {
    let data: [u8;128] = [0, 194, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 147, 26, 5, 0, 0, 0, 1, 17, 178, 126, 118, 166, 174, 122, 210, 42, 187, 10, 30, 84, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]; 
    edwards_from_x_custom::<EdwardsParameters>(&data);
}
```
You can create a `Projective { x: 6582018229284824168619879452488337466666813683795516501084127744, y: 34603871205418659154139976415085657669660745223328262970478166272, t: 0, z: 0 }`, that will make the call to the `to_affine()` function crash.

This happen because the `to_affine()` function is like this

```Rust
// The projective point X, Y, T, Z is represented in the affine coordinates as X/Z, Y/Z.
impl<P: Parameters> From<Projective<P>> for Affine<P> {
    fn from(p: Projective<P>) -> Affine<P> {
        if p.is_zero() {
            Affine::zero()
        } else if p.z.is_one() {
            // If Z is one, the point is already normalized.
            Affine::new(p.x, p.y, p.t)
        } else {
            // Z is nonzero, so it must have an inverse in a field.
            let z_inv = p.z.inverse().unwrap(); // Problem is here
            let x = p.x * z_inv;
            let y = p.y * z_inv;
            let t = p.t * z_inv;
            Affine::new(x, y, t)
        }
    }
}
```

The code check if the projective point is zero, by doing this check:

`self.x.is_zero() && self.y == self.z && !self.y.is_zero() && self.t.is_zero()`, on our input, this check will return `false` , since x is nonzero, the first condition check will result to false, resulting in the whole condition to be false.
So as you said here

> Hm this should not panic; the `inverse` operation should return `None` only when `p.is_zero()` is false, and a non-zero point that's in the subgroup has non-zero z coordinate.

But the inverse function is not called on the whole projective point but on the single z coordinate, which in our case is zero, which will then return None and get unwrapped.

Based on the comment, Z should be nonzero when entering this block but no check is actually made to assert this
