### ISSUE TITLE
[Feature] execute_fee error handling

### ISSUE THREAD

**Issue by liolikus** [AleoHQ/snarkVM#1500]
## 🚀 Feature

`execute_fee` error handling

## Motivation

`thread 'main' panicked at 'Integer subtraction failed on: 1925000u64 and 19000000u64', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkvm-console-network-environment-0.10.3/src/environment.rs:62:9`

Pretty confusing, need to backtrace in order to handle it

## Implementation

`execute_fee` error handling

Full backtrace

```
root@vmi937363:~/leo/examples/token# RUST_BACKTRACE=1 snarkos developer deploy "a.aleo" --private-key "${PRIVATEKEY}" --query "http://vm.aleo.org/api" --path ~/leo/examples/token/build --broadcast "https://vm.aleo.org/api/testnet3/transaction/broadcast" --fee 19000000 --record "{owner: aleo1xvlh6eyf5lgfv2z5za47j6qkh3uv5e0ga6gdzg5l4rssheymxsqqsnkgc4.private, microcredits: 1925000u64.private, _nonce: 1609035081602366234306015320632953007500662107194023270024297071623365229163group.public}"

📦 Creating deployment transaction for 'a.aleo'...

thread 'main' panicked at 'Integer subtraction failed on: 1925000u64 and 19000000u64', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkvm-console-network-environment-0.10.3/src/environment.rs:62:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
   3: snarkvm_console_network_environment::environment::Environment::halt
   4: snarkvm_synthesizer::program::instruction::operation::literals::Literals<N,O,_>::evaluate
   5: snarkvm_synthesizer::process::stack::execute::<impl snarkvm_synthesizer::process::stack::Stack<N>>::execute_function
   6: snarkvm_synthesizer::process::execute_fee::<impl snarkvm_synthesizer::process::Process<N>>::execute_fee
   7: snarkvm_synthesizer::vm::execute::<impl snarkvm_synthesizer::vm::VM<N,C>>::execute_fee
   8: snarkvm_synthesizer::block::transaction::Transaction<N>::deploy
   9: snarkos_cli::commands::developer::deploy::Deploy::parse
  10: snarkos_cli::commands::developer::Developer::parse
  11: snarkos_cli::commands::Command::parse
  12: snarkos::main
```

**Comment by liolikus** [comment]
AFAIK fixed
