### ISSUE TITLE
[Bug] snarkOS memory pool usage of Merkle tree in testing errors

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#175]
## 🐛 Bug Report

![Screen Shot 2021-05-25 at 7 32 32 PM](https://user-images.githubusercontent.com/9260812/119594132-0f9fc000-bd90-11eb-9c99-0cd986e25add.png)

To reproduce the error:
1. cd snarkOS/consensus && git checkout fix/compilation
2. cargo test

**Comment by howardwu** [comment]
Here is a `RUST_BACKTRACE=1` log:
```
---- memory_pool::tests::cleanse_memory_pool stdout ----
thread 'memory_pool::tests::cleanse_memory_pool' panicked at 'range end index 2 out of range for slice of length 1', /Users/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkvm-algorithms-0.3.1/src/merkle_tree/merkle_tree.rs:157:72
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/slice/index.rs:41:5
   3: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /Users/circleci/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:238:13
   4: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /Users/circleci/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:284:9
   5: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /Users/circleci/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
   6: snarkvm_algorithms::merkle_tree::merkle_tree::MerkleTree<P>::rebuild
             at /Users/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkvm-algorithms-0.3.1/src/merkle_tree/merkle_tree.rs:157:72
   7: snarkos_storage::objects::dpc_state::<impl snarkos_storage::ledger::Ledger<T,P,S>>::rebuild_merkle_tree
             at /Users/circleci/code/snarkOS/storage/src/objects/dpc_state.rs:125:9
   8: snarkos_storage::objects::insert_commit::<impl snarkos_storage::ledger::Ledger<T,P,S>>::commit
             at /Users/circleci/code/snarkOS/storage/src/objects/insert_commit.rs:283:9
   9: snarkos_storage::objects::insert_commit::<impl snarkos_storage::ledger::Ledger<T,P,S>>::insert_and_commit
             at /Users/circleci/code/snarkOS/storage/src/objects/insert_commit.rs:316:9
  10: snarkos_consensus::memory_pool::tests::cleanse_memory_pool
             at ./src/memory_pool.rs:401:9
  11: core::ops::function::FnOnce::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by howardwu** [comment]
Resolved by updating usage of `rebuild_merkle_tree`
