### ISSUE TITLE
[Bug] Unable to profile GPU implementation

### ISSUE THREAD

**Issue by unordered-set** [AleoHQ/snarkVM#580]
## Steps to Reproduce

Follow https://github.com/AleoHQ/snarkVM/blob/testnet2/algorithms/src/msm/variable_base/build_guide.md

```
Benchmarking Proof of Succinct Work: Marlin/mine: Warming up for 3.0000 s
Using 'NVIDIA A100-SXM-80GB' as CUDA device with 85198045184 bytes of memory
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Cuda(NoBinaryForGpu)', algorithms/src/msm/variable_base/cuda.rs:183:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1613:5
   3: snarkvm_algorithms::msm::variable_base::cuda::initialize_cuda_request_handler
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

1. Step 1...
2. Step 2...
3. Step 3...

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- snarkVM Version: 48c59e96aa8ba856f48ff0ea62362c2398587f5b
- 
- 
-

**Comment by unordered-set** [comment]
Ah, this is likely because I do have sm_80 GPU
